<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="atulsiaeight-To-be-filled-by-O-E-M" name="megastores.Goto_artisans_and_producers_page_goto_shrujan_detail_view_from_here" tests="1" failures="0" timestamp="27 Feb 2020 12:39:16 GMT" time="63.596" errors="0">
  <testcase name="goto_artisans_producers" time="63.596" classname="megastores.Goto_artisans_and_producers_page_goto_shrujan_detail_view_from_here"/>
</testsuite> <!-- megastores.Goto_artisans_and_producers_page_goto_shrujan_detail_view_from_here -->
